# -*- coding: utf-8 -*-
"""Copy of Sentiment Analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12auRylr1niTvWTZmmRbRX7YvVg865zwe
"""

X_train=["Absolutely terrible, I can't believe I wasted my time on this.",
"Worst movie ever, don't bother watching.",
"I couldn't even finish it, that's how bad it was.",
"A complete disappointment from start to finish.",
"I regretted buying a ticket to this film.",
"The acting was atrocious, and the plot was nonsensical.",
"I expected better, but it fell far short of my expectations.",
"Boring, boring, boring. I couldn't stay awake.",
"A total waste of talent and resources.",
"I don't know how this movie got made.",
"I've seen bad movies, but this one takes the cake.",
"The dialogue was cringeworthy.",
"I would give it zero stars if I could.",
"I wanted my money back after the first 10 minutes.",
"The worst film of the year, hands down.",
"It had potential, but it squandered it.",
"I felt like I lost brain cells watching this.",
"I'll never get those two hours of my life back.",
"The special effects were laughably bad.",
"I wouldn't recommend this to my worst enemy.",
"I can't believe I sat through the whole thing.",
"It was a painful experience from start to finish.",
"The plot had more holes than Swiss cheese.",
"I've seen better acting in a middle school play.",
"I expected a lot more from the director.",
"I had to resist the urge to walk out of the theater.",
"I'm still trying to understand what I just watched.",
"Even the soundtrack was awful.",
"I wouldn't wish this movie on anyone.",
"It made no sense whatsoever.",
"I'd rather watch paint dry.",
"I'm disappointed I wasted my time on this mess.",
"The characters were one-dimensional and uninteresting.",
"I couldn't connect with any of the characters.",
"The script felt like it was written in a hurry.",
"I can't find a single redeeming quality in this film.",
"The cinematography was uninspiring.",
"I've seen better production values on YouTube.",
"The pacing was all over the place.",
"I kept checking my watch, hoping it would end soon.",
"I don't know why this movie exists.",
"It's like they didn't even try to make it good.",
"I'd rather watch a blank screen for two hours.",
"This film left me feeling empty.",
"I had high hopes, but they were crushed.",
"I wouldn't recommend this to anyone, ever.",
"I felt cheated after watching this.",
"I wish I could erase it from my memory.",
"This movie ruined my day.",
"I want a refund for my time and money.",
         "This film is an absolute masterpiece!","The acting is superb, and the storyline is captivating.",
"I couldn't be happier with this movie.","It's a heartwarming story that will stay with you.",
"What a delightful surprise!","I laughed, I cried, and I loved every minute of it.",
"The performances in this film are outstanding.","The chemistry between the lead actors is electrifying.",
"This movie is a must-see for anyone who appreciates great cinema.","It's a true gem.",
"The special effects in this sci-fi epic are mind-blowing.","I was on the edge of my seat the entire time.",
"I haven't been this moved by a movie in years.","It's a true work of art.",
"The soundtrack in this film is simply beautiful.","It adds an extra layer of emotion to an already touching story.",
"I was completely immersed in this movie from start to finish.","It's a cinematic triumph.",
"The direction in this film is top-notch.","Every shot is beautifully composed.",
         "This was really awesome an awesome movie",
           "Great movie! Ilikes it a lot",
           "Happy Ending! Awesome Acting by hero",
           "loved it!",
           "Bad not upto the mark",
           "Could have been better",
           "really Dissapointed by the movie",
           "I found this film to be incredibly boring and uninteresting. The plot dragged on, and I struggled to stay engaged.",
         "This film is an absolute masterpiece!","The acting is superb, and the storyline is captivating.",
"I couldn't be happier with this movie.","It's a heartwarming story that will stay with you.",
"What a delightful surprise!","I laughed, I cried, and I loved every minute of it.",
"The performances in this film are outstanding.","The chemistry between the lead actors is electrifying.",
"This movie is a must-see for anyone who appreciates great cinema.","It's a true gem.",
"The special effects in this sci-fi epic are mind-blowing.","I was on the edge of my seat the entire time.",
"I haven't been this moved by a movie in years.","It's a true work of art.",
"The soundtrack in this film is simply beautiful.","It adds an extra layer of emotion to an already touching story.",
"I was completely immersed in this movie from start to finish.","It's a cinematic triumph.",
"The direction in this film is top-notch.","Every shot is beautifully composed.",
"The cinematography is breathtaking.","I couldn't take my eyes off the screen.",
"The humor in this movie is spot-on.","I laughed out loud throughout the entire film.",
"The characters are relatable and well-developed.","You'll feel like you know them personally.",
"I can't recommend this movie enough.","It's an instant classic.",
"The plot is engaging and full of twists.","I was on the edge of my seat the whole time.",
"This film is a true masterpiece of storytelling.","It's a must-see for any film enthusiast.",
"The chemistry between the lead actors is undeniable.","Their on-screen romance is electric.",
"The dialogue is sharp and witty.","I found myself quoting lines long after the credits rolled.",
"I was pleasantly surprised by this movie.","It exceeded all my expectations.",
"The pacing is perfect.","The story unfolds at just the right speed.",
"The ending is satisfying and leaves you wanting more.","I can't wait for the sequel.",
"The attention to detail in this film is remarkable.","Every frame is a work of art.",
"The score is hauntingly beautiful.","It adds an emotional depth to the film.",
"I was moved to tears by this movie.","It's a heartfelt and emotional journey.",
"The performances are Oscar-worthy.","I wouldn't be surprised if it wins multiple awards.",
"This movie is a triumph of cinema.","It's a must-see for all movie lovers.",
"The direction is flawless.","The filmmaker's vision is clear in every scene.",
"The character development is impressive.","Each character has a unique and compelling arc.",
"I was captivated by this movie from start to finish.","It's a true cinematic experience.",
"The cinematography is stunning.","Every shot is a work of art.",
"The humor is clever and laugh-out-loud funny.","I couldn't stop chuckling.",
"The performances are outstanding.","The cast delivers exceptional acting.",
"This film is a cinematic triumph.","It's a must-see for anyone who appreciates great storytelling.",
"The chemistry between the actors is palpable.","Their on-screen relationship is a joy to watch.",
"The dialogue is sharp and witty.","It's filled with memorable lines.",
"I was pleasantly surprised by this gem of a movie.","It's a hidden treasure.",
"The pacing is perfect, keeping you engaged throughout.","I couldn't look away.",
"The ending is both satisfying and heartwarming.","It leaves you with a smile on your face.",
"The attention to detail is impressive.","The production team clearly put a lot of thought into every aspect.",
"The soundtrack is enchanting and adds depth to the story.","It's a true cinematic experience.",
"The performances are exceptional.","The actors bring their characters to life beautifully.",
"I can't recommend this film enough.","It's a true masterpiece.",
"The direction is top-notch.","Every frame is meticulously crafted.",
"The character development is superb.","You'll feel a connection to each character.",
"I was completely enthralled by this movie.","It's a cinematic masterpiece.",
"The cinematography is breathtaking.","It's a visual feast for the eyes.",
"The humor is clever and well-executed.","I found myself laughing throughout.",
"The performances are remarkable.","The cast truly shines.",
"This film is a true gem of cinema.","It's a must-see for movie enthusiasts.",
"The chemistry between the lead actors is undeniable.","Their on-screen presence is magnetic."


         ]

y_train=["negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
 "negative",
         "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
         "positive","positive","positive","positive","negative","negative","negative","negative",

         "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",

]

X_train # Reviews

"""# Cleaning of the data"""

# Tokenize
# "I am a python dev" -> ["I", "am", "a", "python", "dev"]

from nltk.tokenize import RegexpTokenizer
# NLTK -> Tokenize -> RegexpTokenizer

# Stemming
# "Playing" -> "Play"
# "Working" -> "Work"

from nltk.stem.porter import PorterStemmer
# NLTK -> Stem -> Porter -> PorterStemmer

from nltk.corpus import stopwords
# NLTK -> Corpus -> stopwords

# Downloading the stopwords
import nltk
nltk.download('stopwords')

tokenizer = RegexpTokenizer(r"\w+")
en_stopwords = set(stopwords.words('english'))
ps = PorterStemmer()

def getCleanedText(text):
  text = text.lower()

  # tokenizing
  tokens = tokenizer.tokenize(text)
  new_tokens = [token for token in tokens if token not in en_stopwords]
  stemmed_tokens = [ps.stem(tokens) for tokens in new_tokens]
  clean_text = " ".join(stemmed_tokens)
  return clean_text

"""# Input from the user"""

X_test = ["I can't believe I wasted two hours of my life on this film. The plot was incoherent, and the characters were one-dimensional.",

"This movie had so much potential, but it fell flat. The dialogue was cringeworthy, and the pacing was all over the place.",

"I was expecting a gripping thriller, but what I got was a predictable and formulaic story with no surprises.",

"The special effects were terrible, and the CGI was so poorly done that it took me out of the movie completely.",

"I've never seen a film with so many plot holes. It felt like the writers didn't even bother to check their own story for consistency.",

"The acting was atrocious, and it was clear that the cast was just going through the motions. I couldn't wait for it to end.",

"This movie was a complete waste of money. I wouldn't recommend it to anyone, even as a joke.","good movie","This film is an absolute masterpiece!","The acting is superb, and the storyline is captivating."
"I couldn't be happier with this movie.","It's a heartwarming story that will stay with you.",
"What a delightful surprise!","I laughed, I cried, and I loved every minute of it.",
"The performances in this film are outstanding.","The chemistry between the lead actors is electrifying.",
"This movie is a must-see for anyone who appreciates great cinema.","It's a true gem.",
"The special effects in this sci-fi epic are mind-blowing.","I was on the edge of my seat the entire time.",
"I haven't been this moved by a movie in years.","It's a true work of art.",
"The soundtrack in this film is simply beautiful.","It adds an extra layer of emotion to an already touching story.",
"I was completely immersed in this movie from start to finish.","It's a cinematic triumph.",
"The direction in this film is top-notch."]

X_clean = [getCleanedText(i) for i in X_train]
xt_clean = [getCleanedText(i) for i in X_test]

X_clean

# Data before cleaning
'''
X_train = ["This was awesome an awesome movie",
           "Great movie! Ilikes it a lot",
           "Happy Ending! Awesome Acting by hero",
           "loved it!",
           "Bad not upto the mark",
           "Could have been better",
           "Dissapointed by the movie"]
'''

"""# Vectorize"""

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(ngram_range = (1,2))
# "I am PyDev" -> "i am", "am Pydev"

X_vec = cv.fit_transform(X_clean).toarray()

X_vec

print(cv.get_feature_names_out())

Xt_vect = cv.transform(xt_clean).toarray()

Xt_vect

"""# Multinomial Naive Bayes"""

from sklearn.naive_bayes import MultinomialNB

mn = MultinomialNB()

mn.fit(X_vec, y_train)

y_pred = mn.predict(Xt_vect)

y_pred

from sklearn.metrics import accuracy_score,precision_score,f1_score
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
X_train_vec, X_test_vec, y_train_vec, y_test_vec = train_test_split(X_vec, y_train, test_size=0.2, random_state=42)
# Define the true labels for the test data
true_labels = ["negative","negative","negative","negative","negative","negative","negative","positive",
               "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive","positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 "positive",
 ]

# Calculate the accuracy score
accuracy = accuracy_score(true_labels, y_pred)

print("Accuracy Score:", accuracy)

import matplotlib.pyplot as plt

# List of model names
models = ["Multinomial", "svm", "random forest", ]

# List of corresponding accuracy scores
accuracies = [0.8846153846153846, 0.884615384615384,0.8846153846153846,]

# Create a bar chart
plt.figure(figsize=(7, 10))
plt.bar(models, accuracies, color=['blue', 'green', 'red', 'purple'])

# Add labels and title
plt.xlabel('Models')
plt.ylabel('Accuracy')
plt.title('Comparison of Model Accuracy')

# Display the plot
plt.ylim(0, 1)  # Set the y-axis range from 0 to 1 for accuracy scores
plt.show()

#multinomial
mn = MultinomialNB()
mn.fit(X_vec, y_train)
y_pred = mn.predict(Xt_vect)
accuracy = accuracy_score(true_labels, y_pred)

print("Accuracy Score:", accuracy)

svm = SVC(kernel='linear', C=1)
svm.fit(X_train_vec, y_train_vec)
y_pred = svm.predict(Xt_vect)
accuracy = accuracy_score(true_labels, y_pred)

print("Accuracy Score:", accuracy)

rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_vec, y_train)
y_pred = rf.predict(Xt_vect)
accuracy = accuracy_score(true_labels, y_pred)
print("accuracy=",accuracy)